### ISSUE TITLE
Filesystem emulation, Error: this should be unreachable

### ISSUE THREAD

**Issue by gdmiron** [leaningtech/cheerp-meta#100]
I am trying to make a simple test using the "Filesystem emulation". As soon as I add `cheerp::FilePreloader files(preloadCallback, "CemHyds-dat.lst");` to my test file I get the following error in the broswer:
```
Uncaught (in promise) Error: this should be unreachable
    __dummy http://127.0.0.1:8080/gemsw.js:57
    promise http://127.0.0.1:8080/gemsw.js:78
    promise callback* http://127.0.0.1:8080/gemsw.js:69
```
I am wondering if someone else can preproduce this error or there is something that I do wrong. 
See: [test-wasm2.zip](https://github.com/leaningtech/cheerp-meta/files/5311335/test-wasm2.zip)

I used: `Cheerp 1601094897-1~bionic clang version 9.0.0  (based on LLVM 9.0.0svn)`

**Comment by gdmiron** [comment]
If someone could try to test the example I attached and see if the error can be reproduced (compile and test in the browser). Thanks.

**Comment by alexp-sssup** [comment]
It is not possible for us to reproduce this problem without additional information.

What is the exact build command you are using?

Please verify that the filesystem emulation library has been correctly linked: ```-lposixcompat``` should be passed during the linking step.

**Comment by gdmiron** [comment]
Thanks @alexp-sssup! this solves the problem.
