### ISSUE TITLE
[Feature request] -cheerp-make-module=typescript or ES6

### ISSUE THREAD

**Issue by sdykae** [leaningtech/cheerp-meta#102]
ES6 modules?
import { add } from "./file.js";
import { add } from "./file.ts"; (with tipes :(?)

**Comment by carlopi** [comment]
Hi @sdykae, ES6 support was on our wish-list and it was recently merged into [Cheerp](https://github.com/leaningtech/cheerp-compiler).

An explanation of the feature is here: https://leaningtech.github.io/cheerp-meta/pages/ES6-Modules.

ES6 modules generated by Cheerp will have as default export an initializing function: [example](https://leaningtech.github.io/cheerp-meta/pages/ES6-Modules#how-to-use-es6-modules-generated-by-cheerp).

Basic syntax:
```javascript
import instantiate from './add.js'

var module = await instantiate();
var add = module.add;
console.log(add(23, 23));
```

The syntax you suggest is available by composing the original module with a wrapper module: complete example on [GitHub's Gist](https://gist.github.com/carlopi/6b38fe1f2347a8cd712a9e9ff83c47ad)

Composed syntax:
```javascript
import instantiate from './add.js'

var module = await instantiate();
var add = module.add;

export {add};
```
then
```javascript
import {add} from "./wrap_add.js"

console.log(add(23, 19));
```
