### ISSUE TITLE
Missing header in cheerp-compiler source

### ISSUE THREAD

**Issue by bradwhitehead2** [leaningtech/cheerp-meta#105]
Using cheerp 2.6 and gcc (GCC) 11.1.1 20210428 (Red Hat 11.1.1-1), and following the Linux build instructions, the compiler compilation errors out with:

```
> ```
In file included from ~/cheerp/cheerp-compiler/llvm/utils/benchmark/src/benchmark_register.cc:15:
> ~/cheerp/cheerp-compiler/llvm/utils/benchmark/src/benchmark_register.h: In function ‘void AddRange(std::vector<T>*, T, T, int)’:
> ~/cheerp/cheerp-compiler/llvm/utils/benchmark/src/benchmark_register.h:17:30: error: ‘numeric_limits’ is not a member of ‘std’
>    17 |   static const T kmax = std::numeric_limits<T>::max();
>       |                              ^~~~~~~~~~~~~~

```
```
This is followed by several subsequent errors, traceable to the failed std::numeric_limits compile
 
The problem is that the reference to the limits header is missing from 'cheerp-compiler/llvm/utils/benchmark/src/benchmark_register.h'

Solution, add `'#include <limits>'` to 'cheerp-compiler/llvm/utils/benchmark/src/benchmark_register.h' and re-run ninja.  Compile goes to completion.

**Comment by carlopi** [comment]
Thanks for signaling + fixing this problem.
This commit in LLVM upstream: https://github.com/llvm/llvm-project/commit/b498303066a63a203d24f739b2d2e0e56dca70d1 has exactly the same fix you found, I will check with the team but I think we will cherry-pick it so as to include the fix.

Thanks again, we look forward to any other feedback you might have on Cheerp

**Comment by carlopi** [comment]
It's fixed in the current master:
[https://github.com/leaningtech/cheerp-compiler/commit/6b1ff4f34c5d3ad1a7dc7700f779a9aa88a04a43](https://github.com/leaningtech/cheerp-compiler/commit/6b1ff4f34c5d3ad1a7dc7700f779a9aa88a04a43).
