### ISSUE TITLE
More documentation about conversion between C++ and Javascript objects

### ISSUE THREAD

**Issue by niansa** [leaningtech/cheerp-meta#108]
It always took me really long to figure out how to convert or even being unable to figure it out like in #107.
More documentation about that stuff would be awesome.

**Comment by carlopi** [comment]
Hi @niansa, our documentation is currently a Wiki on this same repo ([main page](https://github.com/leaningtech/cheerp-meta/wiki)).

There is plenty of useful information on the wiki, but we will gladly consider any feedback for improvements / areas to be covered.

Possibly [this page](https://github.com/leaningtech/cheerp-meta/wiki/Conversion-between-arrays-and-Typed-Arrays) was the closer to discuss the problems you were facing, and could be integrated.
