### ISSUE TITLE
Can cheerp interact with canvas pixel data

### ISSUE THREAD

**Issue by fishinTyme** [leaningtech/cheerp-meta#11]
I've read through the documentation of cheerp compiler and I see that cheerp allows you to interact with several dom elements even in the C++ "world". 

Is it possible to pass an array buffer of image data populated in "regular javascript" with the getImageData command, and pass that data off to cheerp compiled javascript? 

I'm basically wondering if you can use cheerp's speed to improve canvas pixel manipulation performance. Thank you!

**Comment by alexp-sssup** [comment]
Hello, you can try something like this

```
client::ImageData* imageData = _2dCtx->getImageData(0,0,width,height);
uint8_t* canvasPixels = __builtin_cheerp_make_regular<uint8_t>(imageData->get_data(), 0);
```

The __builtin_cheerp_make_regular converts a typed array to a normal C++ array without copying it, so now the canvasPixel pointer alias the JavaScript buffer.

**Comment by alexp-sssup** [comment]
As of the current version of Cheerp, this is the solution that we advise:

```
client::ImageData* imageData = _2dCtx->getImageData(0,0,width,height);
uint8_t* canvasPixels = __builtin_cheerp_make_regular<uint8_t>(new client::Uint8Array(imageData->get_data()), 0);
```
