### ISSUE TITLE
Arm64 Support?

### ISSUE THREAD

**Issue by darkoverlordofdata** [leaningtech/cheerp-meta#112]
When I try to install from the repo, apt update throws an err 93, its unable to find the arm64 version for the package,
When I try to compile from source, the compiler has a segment fault about 15 minutes into the build. 

Do you have any plans to support ARM64?

**Comment by carlopi** [comment]
Hi @darkoverlordofdata, thanks for the feedback, a colleague is exploring whether generating packages for arm could fit in the pipeline-rework that it's currently being done

**Comment by saarikoski-jules** [comment]
An ARM64 build is now available on the nightly build PPA. With the next release of Cheerp, it will also become available as a stable version.
