### ISSUE TITLE
Avx/Avx2 support?

### ISSUE THREAD

**Issue by ouya99** [leaningtech/cheerp-meta#113]
Hello,

does cheerp support SIMD avx/avx2 instructions?
 Did not find any help on this on the internet nor in github

thanks

**Comment by yuri91** [comment]
Hi!

Cheerp currently does not support SIMD, although we plan to implement it in the future.

In particular about avx/avx2: they are x86-specific, so some sort of compatibility layer on top of native Wasm SIMD instructions would be needed, even after we implement the latter.

We will update[ this issue](https://github.com/leaningtech/cheerp-meta/issues/110) when there will be progress on this feature.
