### ISSUE TITLE
Problems encountered when building cheerp

### ISSUE THREAD

**Issue by unicornt** [leaningtech/cheerp-meta#116]
I try to build cheerp according to [build-instructions](https://docs.leaningtech.com/cheerp/Linux-build-instructions). However, I meet some problems.

# Problem 1
In "Build utilities and libraries" section. When running instruction "ninja -C build_runtimes_genericjs", it will report no member error.
![5d770280e7298fd755d17085d4d2256](https://user-images.githubusercontent.com/18662046/177486056-de6a6814-ae32-4890-9e02-3b69db93447b.png)
I fix it by removing this code.

# Problem 2
In "Build utilities and libraries" section. When running instruction "make -C stdlibs install INSTALL_PREFIX=/opt/cheerp CHEERP_PREFIX=/opt/cheerp". It will report no rule error.
![61bbd0c918d76fed765997314836800](https://user-images.githubusercontent.com/18662046/177487407-7faf6da6-da8f-4ee6-b1cd-ad8d882b8f9e.png)
I fix it by removing "crt1.bc" from Makefile.

# Problem 3
After building successfully, when trying to compile C++ file, it will report no file error.
![image](https://user-images.githubusercontent.com/18662046/177487026-86237ed3-7128-412a-8b71-3f0cffd1fcd4.png)

I have fixed all of them and built cheerp successfully, but i am not sure if i do it right and why these problem would arise. These problems is because of bad environment configuration, or failure in these instructions?

**Comment by unicornt** [comment]
In Problem 2, do you mean [cheerp-musl](https://github.com/leaningtech/cheerp-musl)?
I didn't see it in [Installation instructions](https://docs.leaningtech.com/cheerp/Linux-build-instructions).

**Comment by unicornt** [comment]
> Hi @unicornt, thanks for trying Cheerp, and reporting back the problems you were faced with.
> 
> Problem 1: I think I have a fix, will check and come back to it in a bit.
> 
> Problem 2: The file crt1.bc should be genertated during cheerp-musl build step, and then found both at /opt/cheerp/lib/genericjs/crt1.bc and at /opt/cheerp/lib/asmjs/crt1.bc Could you possibly check whether this was the case?
> 
> Problem 3: I still have to check, unsure what's happening, the file libsystem.bc should also be listed in /opt/cheerp/bin/../lib/asmjs/libsystem.bc.

In Problem 2, do you mean [cheerp-musl](https://github.com/leaningtech/cheerp-musl)?
I didn't see it in [Installation instructions](https://docs.leaningtech.com/cheerp/Linux-build-instructions).

**Comment by carlopi** [comment]
Yes, we recently moved from newlib to musl as the backing libc implementation.

Thanks for pointing out that the documentation is outdated, I will fix it now, this probably generates all 3 problems.

I will ping when the documentation is update.


By the way, probably the simplest way to get started with Cheerp development is using PPAs, also available for nightly builds.

**Comment by carlopi** [comment]
I believe all 3 problem are connected to the switch to musl.

I changed the build instructions to point to the latest stable release, Cheerp 2.7, that still uses cheerp-newlib: https://docs.leaningtech.com/cheerp/Linux-build-instructions.

Thanks you again for noticing, looking forward for other feedback you might have on Cheerp.
