### ISSUE TITLE
bit field initialize fail

### ISSUE THREAD

**Issue by zyz9740** [leaningtech/cheerp-meta#119]
[bit_field_initialize_fail.zip](https://github.com/leaningtech/cheerp-meta/files/9117009/bit_field_initialize_fail.zip)

Please look at this bug as well,  I don't know why I can't initialize the bit filed in union.
Note that if the type of variable b is long or int, it can be initialized as expected.

**Comment by carlopi** [comment]
Thanks for opening the issue, I do reproduce the bug.

**Comment by alexp-sssup** [comment]
The problem is now fixed in Cheerp master
