### ISSUE TITLE
How to debug cheerp using GDB?

### ISSUE THREAD

**Issue by hungryzzz** [leaningtech/cheerp-meta#122]
Hi, I want to debug cheerp using GDB, what should I do? 

Can I use `-DCMAKE_BUILD_TYPE=Debug` when I build cheerp-compiler? Does this work?

Thanks!

**Comment by carlopi** [comment]
I would expect for this to work for any non-Release build, more as in for regular clang/LLVM, there are a few places in the internet discussing the specifics (like: https://stackoverflow.com/questions/2226112/debugging-an-llvm-pass-with-gdb, but probably there have to be other resources).

Consider that the packages we provided are builded in Release mode, so you will need to build from source, and I recommend doing that on tag cheerp-2.7 (as detailed here: https://docs.leaningtech.com/cheerp/Linux-build-instructions).
