### ISSUE TITLE
Segmentation fault in  cheerp::ConstantExprLoweringPass

### ISSUE THREAD

**Issue by zyz9740** [leaningtech/cheerp-meta#129]
[crash_infinite_loop_2.zip](https://github.com/leaningtech/cheerp-meta/files/9762763/crash_infinite_loop_2.zip)

Another case that can cause segmentation fault, which  seems different to the later.

**Comment by carlopi** [comment]
Thanks for raising also this case!

I reproduce, this is connected with ConstantExprLowering::visitConstantExpr, later I will take a closer look.

**Comment by carlopi** [comment]
Fixed in the current Cheerp's nightly (https://launchpad.net/~leaningtech-dev/+archive/ubuntu/cheerp-nightly-ppa/+packages).
Closing this, thanks.
