### ISSUE TITLE
How can I keep the javascript variable in a vector?

### ISSUE THREAD

**Issue by MegaJsTeam** [leaningtech/cheerp-meta#13]
How can I keep the javascript variable in a vector? You have a wrapper like JsVariavle class?

```cpp
vector <AnyJsVarWrapper> items;
```

and
AnyJsVarWrapper::null();  // returns wrapper to null

AnyJsVarWrapper number = new AnyJsVarWrapper(100);
number.toString() e.t.c.

maybe cheerp::Object ?

**Comment by MegaJsTeam** [comment]
https://monosnap.com/file/NWJnDm4lvkESsbcM2nNXPN3eWOI9dK.png
![image](https://cloud.githubusercontent.com/assets/17149958/13517845/773649e4-e1d8-11e5-9165-814c2ff5cca2.png)

**Comment by MegaJsTeam** [comment]
![image](https://cloud.githubusercontent.com/assets/17149958/13557404/aaca8674-e400-11e5-8370-339600a81d17.png)

error: too many arguments to function call, expected 1, have 2
                handler(&q, &q);
                ~~~~~~~     ^~

**Comment by MegaJsTeam** [comment]
you are welcome. remove your repository! Do not deceive people!

**Comment by alexp-sssup** [comment]
From the C++ code point of view JavaScript objects behave like pointers or C++ references. You can easily use std::vector<client::Object* /*Or any type you want*/>. Similarly you can store client object pointers in std::map or plain C++ arrays.
