### ISSUE TITLE
crash in shouldDiscardValueNames

### ISSUE THREAD

**Issue by zyz9740** [leaningtech/cheerp-meta#133]
[crash_shouldDiscardValueNames.zip](https://github.com/leaningtech/cheerp-meta/files/9827116/crash_shouldDiscardValueNames.zip)

You can try this case.

**Comment by zyz9740** [comment]
A more consice version: 

```
#include <stdio.h>

int main() {
  strcpy(0, "cd");
  return 0;
}
```

It's indeed invalid usage of strcpy function but may not cause crash

**Comment by Hyxogen** [comment]
Although neither crashes seemed to be happening anymore, the case attached in the zip did cause a hang, which was fixed in: https://github.com/leaningtech/cheerp-compiler/commit/0efaba0e382e4d3f6d69d615357a22eb4b5eeb7d
