### ISSUE TITLE
Suggestion: emit TypeScript type declarations

### ISSUE THREAD

**Issue by bates64** [leaningtech/cheerp-meta#146]
Fairly large feature I expect but it'd be awesome if you could pass a flag to `clang++` to generate [TypeScript declarations](https://www.typescriptlang.org/docs/handbook/2/type-declarations.html) for the module.

e.g.
```
clang++ -target cheerp-wasm file.c -o file.js -cheerp-make-types=file.d.ts
```
To emit a `file.d.ts` looking something like:
```typescript
export type InstanciateOptions = {
    buffer: /* some typed array */,
} | {
    absPath: string | URL,
}

export default function instanciate(options: InstanciateOptions?): Promise<{}>
```
(And for `[jsexport]`'d things, export types for those funcs)

**Comment by DutChen18** [comment]
Added in https://github.com/leaningtech/cheerp-compiler/pull/162
