### ISSUE TITLE
Basic

### ISSUE THREAD

**Issue by dgu123** [leaningtech/cheerp-meta#15]
Hello

it s not really an issue, but would you provide a sample with basic shader loading using your api?
Kind regards
dav

**Comment by alexp-sssup** [comment]
This is a basic WebGL example that include shader loading https://github.com/leaningtech/cheerp-utils/blob/master/tests/webgl/webgl.cpp. If you want to dynamically load shader files you can use XMLHttpRequest (https://github.com/leaningtech/cheerp-meta/wiki/Browser-side-programming-guide#loading-data-xmlhttprequest)

**Comment by dgu123** [comment]
Thanks a lot, i will do a model rendering to see how it feel , i mean how it s need to be coded, your project is really great.
