### ISSUE TITLE
Window should implement IDBEnvironment

### ISSUE THREAD

**Issue by HighCommander4** [leaningtech/cheerp-meta#16]
Shouldn't Window implement IDBEnvironment, as described [here](https://developer.mozilla.org/en-US/docs/Web/API/IDBEnvironment)? Otherwise, how can a Cheerp application access the IndexedDB API?

**Comment by HighCommander4** [comment]
I see that casting `&window` to `IDBEnvironment*` works, even though the inheritance is not reflected in the C++ types. However, this produces a warning: "Cheerp: Using values casted to unrelated types is undefined behaviour unless the destination type is the actual type of the value". Is there a way to write the code that doesn't produce the warning?

**Comment by alexp-sssup** [comment]
You should be able to use client::indexedDB directly, does it work for you?

**Comment by HighCommander4** [comment]
Yes, that works, thanks!

(Sorry, I am new to web development and I forgot that properties of "window" are also accessible as global names.)
