### ISSUE TITLE
Add support for the second edition of the IndexedDB API

### ISSUE THREAD

**Issue by HighCommander4** [leaningtech/cheerp-meta#17]
The IndexedDB API has a [second edition](https://w3c.github.io/IndexedDB/) which supports some new methods like [`IDBObjectStore.getAllKeys()`](https://w3c.github.io/IndexedDB/#dom-idbobjectstore-getallkeys). It would be nice if Cheerp exposed these new methods.

**Comment by alexp-sssup** [comment]
Thanks for reporting this, we will add support for this in the next release. In general you should be able to extend Cheerp to currently non stock supported API by declaring the appropriate classes in the ```client``` namespace. See https://github.com/leaningtech/cheerp-meta/wiki/Browser-side-programming-guide#accessing-the-dom-under-the-hood for an example.

**Comment by HighCommander4** [comment]
In this case, the new functionality is not a new class, but a new method of an existing class (`IDBObjectStore`). Is that still something I can declare myself?

**Comment by alexp-sssup** [comment]
You should be able to derive a new class from the original one and access the new method by pointer casting.

**Comment by HighCommander4** [comment]
Thanks, that works!

I assume I should keep the report open to track Cheerp adding support for it directly.

**Comment by DutChen18** [comment]
`IDBObjectStore.getAllKeys()` was added in https://github.com/leaningtech/cheerp-utils/commit/71a1a5411b678dfaaebef354de71ab3cafe98bae
