### ISSUE TITLE
Global String objects do not work

### ISSUE THREAD

**Issue by HighCommander4** [leaningtech/cheerp-meta#18]
When I compile the following program:

```
#include <cheerp/client.h>
#include <cheerp/clientlib.h>

using namespace client;

String foo{"foo"};

void webMain()
{
    document.addEventListener("DOMContentLoaded", cheerp::Callback([](Event*)
    {
        console.log(String("performing getElementById on ").concat(&foo));
        HTMLElement* result = document.getElementById(foo);
        if (!result)
            console.log("element does not exist");
    }));
}
```

and use it with the following HTML file:

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <script src="test.js"></script>
  </head>
  <body><div id="foo"></body>
</html>
```

I get the following printed in the devtools console:

> "performing getElementById on [object Object]"
> "element does not exist"

It works if I make `foo` a local variable, or a pointer to a heap-allocated `String`. Why does a global `String` object not work?

**Comment by alexp-sssup** [comment]
Thanks for reporting this bug, initializing client objects in the global scope is not currently supported. You can use the following syntax though: ```String* foo = new String("foo");```

**Comment by alexp-sssup** [comment]
This issue is fixed in current master, proper errors are now reported when trying to use ```client``` types unless through pointers and references.
