### ISSUE TITLE
Cannot use IDBCursor._continue() method

### ISSUE THREAD

**Issue by HighCommander4** [leaningtech/cheerp-meta#19]
`IDBCursor` has a [`continue()` method](https://developer.mozilla.org/en-US/docs/Web/API/IDBCursor/continue), which is declared in C++ as `_continue()` (because `continue` is a C++ keyword).

However, whenever I try calling this method in C++, I get the following error when running the generated JS code: 

> TypeError: a._continue is not a function

It looks like the C++ to JS translation is not removing the underscore.

**Comment by HighCommander4** [comment]
Thankfully, the bug is easy to work around. Declare a C++ function with a different name in namespace `client`:

```
namespace client
{
    void continueCursor(IDBCursor*);
}
```

Implement it in JS:

```
function continueCursor(cursor) {
  cursor.continue();
}
```

and then use `continueCursor(cursor)` instead of `cursor._continue()` at the C++ call site.

**Comment by alexp-sssup** [comment]
Thanks for reporting this bug and proposing a workaround. We will fix the issue as soon as possible.

**Comment by HighCommander4** [comment]
`IDBObjectStore._delete` has a similar issue.

**Comment by carlopi** [comment]
I didn't realize that this has been solved a while ago with the additions of the [[cheerp::interface_name("some_name")], see for example: https://github.com/leaningtech/cheerp-utils/blob/master/include/client/clientlib.h#L11740.

**Comment by carlopi** [comment]
Interface names work has been driven by this issue, thanks for helping point out this problem.
