### ISSUE TITLE
Problem using std::map

### ISSUE THREAD

**Issue by rkennaway** [leaningtech/cheerp-meta#2]
Minimal example:

    #include <map>

    void test() {
        std::map<int,int> theMap;
        theMap[1] = 2;
    }

Compiler invocation:

    /opt/cheerp/bin/clang++ -target cheerp test.cpp -o test.js

Output:

    In file included from test.cpp:1:
    In file included from /opt/cheerp/include/c++/v1/map:423:
    In file included from /opt/cheerp/include/c++/v1/__tree:16:
    /opt/cheerp/include/c++/v1/memory:1664:13: error: no matching function for call
          to 'operator new'
                ::new(__p) _Up(_VSTD::forward<_Args>(__args)...);
                ^~
    /opt/cheerp/include/c++/v1/memory:1591:18: note: in instantiation of function
          template specialization
          'std::allocator<std::__tree_node<std::__value_type<int, int>, void *>
          >::construct<const int, int>' requested here
                {__a.construct(__p, _VSTD::forward<_Args>(__args)...);}
                     ^
    /opt/cheerp/include/c++/v1/memory:1472:14: note: in instantiation of function
          template specialization
          'std::allocator_traits<std::allocator<std::__tree_node<std::__value_type<int,
          int>, void *> > >::__construct<const int, int>' requested here
                {__construct(__has_construct<allocator_type, pointer, _Args...>(),
                 ^
    /opt/cheerp/include/c++/v1/map:1328:20: note: in instantiation of function
          template specialization
          'std::allocator_traits<std::allocator<std::__tree_node<std::__value_type<int,
          int>, void *> > >::construct<const int, int>' requested here
        __node_traits::construct(__na, _VSTD::addressof(__h->__value_.__cc.f...
                       ^
    /opt/cheerp/include/c++/v1/map:1396:29: note: in instantiation of member
          function 'std::map<int, int, std::less<int>,
          std::allocator<std::pair<const int, int> > >::__construct_node_with_key'
          requested here
            __node_holder __h = __construct_node_with_key(_VSTD::move(__k));
                                ^
    test.cpp:10:11: note: in instantiation of member function 'std::map<int, int,
          std::less<int>, std::allocator<std::pair<const int, int> > >::operator[]'
          requested here
        theMap[1] = 2;
              ^
    /opt/cheerp/include/c++/v1/new:145:40: note: candidate function not viable: no
          known conversion from 'const int *' to 'void *' for 2nd argument; take the
          address of the argument with &
    inline _LIBCPP_INLINE_VISIBILITY void* operator new  (std::size_t, void...
                                           ^
    /opt/cheerp/include/c++/v1/new:132:30: note: candidate function not viable: no
          known conversion from 'const int *' to 'const std::nothrow_t' for 2nd
          argument
    _LIBCPP_NEW_DELETE_VIS void* operator new(std::size_t __sz, const std::n...
                                 ^
    /opt/cheerp/include/c++/v1/new:127:30: note: candidate function not viable:
          requires single argument '__sz', but 2 arguments were provided
    _LIBCPP_NEW_DELETE_VIS void* operator new(std::size_t __sz)
                                 ^
    1 error generated.

**Comment by alexp-sssup** [comment]
It should be fixed on current master and upcoming Cheerp 1.2
