### ISSUE TITLE
How do I create an ErrorEventHandler from a C++ function?

### ISSUE THREAD

**Issue by HighCommander4** [leaningtech/cheerp-meta#20]
`window` has an [`onerror` property](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onerror#window.onerror) that can be overridden to provide custom behaviour when a JS runtime error occurs. The type of this property is `ErrorEventHandler`.

How can I create an `ErrorEventHandler` object from a C++ function or lambda?

**Comment by alexp-sssup** [comment]
Something like ```set_onerror((client::ErrorEventHandler*)cheerp::Callback(cppFunc))``` should work, give it a try.

**Comment by HighCommander4** [comment]
That works, thanks. However, it gives a warning:

> warning: Cheerp: Using values casted to unrelated types is undefined behaviour unless the destination type is the actual type of the value

Is there a way to avoid this warning?

**Comment by alexp-sssup** [comment]
As of Cheerp master there is a special attribute to mark a cast as known to be safe, for example

```
client::window.set_onerror((client::ErrorEventHandler [[cheerp::safe_cast]] *)cheerp::Callback(cppFunc));
```
