### ISSUE TITLE
Cannot create an HTMLOptionElement

### ISSUE THREAD

**Issue by HighCommander4** [leaningtech/cheerp-meta#21]
I'm unable to create an `HTMLOptionElement` object from C++ code.

`new client::HTMLOptionElement()` produces the following error in the console:

> TypeError: Illegal constructor.

The Web API docs say that `HTMLOptionElement` needs to be constructed using the special constructor [`Option`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOptionElement/Option), but this does not appear in the Cheerp API.

I notice there is an `HTMLOptionElement::create()` method, but it requires a pre-existing `HTMLOptionElement` object.

**Comment by alexp-sssup** [comment]
HTML elements can be created using ```client::document.createElement("option"/*or any other tag name*/)```

**Comment by HighCommander4** [comment]
Thanks. (Again, sorry, new to web development here.)
