### ISSUE TITLE
client::String::indexOf() should be const

### ISSUE THREAD

**Issue by HighCommander4** [leaningtech/cheerp-meta#22]
Currently, `client::String::indexOf()` is not const, even though logically it should be. This is unfortunate because it means I cannot call `indexOf()` on a `const client::String&` parameter to a function.

**Comment by alexp-sssup** [comment]
This does make sense, but considering that strings are immutable maybe we should make all methods const.

**Comment by alexp-sssup** [comment]
Fixed in current master
