### ISSUE TITLE
What is the recommended way of passing around client::String in C++ code?

### ISSUE THREAD

**Issue by HighCommander4** [leaningtech/cheerp-meta#23]
Let's say my C++ code has an internal interface (meaning, a function called by other C++ code) that takes a string as an argument. To minimize expensive conversions between `std::string` and `client::String`, I want to use `client::String` as the string type.

What is the recommended way of passing around the `client::String`?

The first thing I tried is to pass by const reference, the way the cheerp APIs do:

`void myFunction(const client::String& s);`

However, I ran into a few issues:

- I cannot call certain methods on `s`, like `indexOf()`. (This one's likely a [bug](https://github.com/leaningtech/cheerp-meta/issues/22)).
- Some APIs like `Array::push()` require an `Object*`. I need to cast away constness to get an `Object*` from a `const String&`.

The next thing I tried is to pass by pointer:

`void myFunction(client::String* s);`

However, this has its issues too:

 - I can no longer pass a string literal as an argument.

What do you recommend using?

**Comment by alexp-sssup** [comment]
The recommended way is to use pointers. const references are only used to get implicit conversions for the APIs. You can generate a String from a cons char* with the normal ```new String("literal")``` syntax.

**Comment by HighCommander4** [comment]
> You can generate a String from a cons char* with the normal `new String("literal")` syntax.

That's not as good as a native C++ version of the function, which would take `const std::string&` and accept a string literal as an argument directly, without having to wrap it in anything.

Perhaps it would make sense to make `cheerp::String` a "handle" type, which could be passed around by value, without incurring a copy of the string? Then functions could simply take `String` by value, which is as simple as it gets, and a string literal could be passed as an argument.

**Comment by alexp-sssup** [comment]
Having only client::String as an handle type would be inconsistent. We may consider having all client types as handles, but that requires some engineering to figure out pros and cons. You may be able to write your own small "smartptr" that wraps a String and provides the interface you want.

**Comment by HighCommander4** [comment]
Fair enough, thanks.
