### ISSUE TITLE
new TArray<String>() does not work

### ISSUE THREAD

**Issue by HighCommander4** [leaningtech/cheerp-meta#24]
There is a `TArray<T>` class in the cheerp API, but when I try to create an instance of one using e.g. `new TArray<String>()` I get:

> ReferenceError: TArray is not defined

**Comment by alexp-sssup** [comment]
TArray is not a real browser type, it's designed to be used by explicitly casting an existing Array to a TArray<T>.

**Comment by HighCommander4** [comment]
OK, thanks for clarifying. It might make sense to mention this in the documentation.

**Comment by alexp-sssup** [comment]
The issue is fixes in master, you can now allocate a TArray<> type that will be backed by a normal client Array
