### ISSUE TITLE
Some String APIs are not exposed (e.g. localeCompare())

### ISSUE THREAD

**Issue by HighCommander4** [leaningtech/cheerp-meta#25]
The `String` class has some methods, like [`localeCompare()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare), which are not exposed in the Cheerp API.

It would be nice to expose these so C++ code can call them easily.

**Comment by HighCommander4** [comment]
Also comparison operators.

What is the recommended way of comparing two strings for equality?

**Comment by HighCommander4** [comment]
And the same for some `Array` APIs, like [`slice()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice).

**Comment by alexp-sssup** [comment]
To compare client::String you can compare the respective pointers. Comparing against other string data types requires a conversion at this time. A side note, creating client::String from a C++ string literal is a cheap operation as the compiler backend will optimize it away to a JS literal. You are right about APIs currently missing, we will make sure to add them in the next release.

**Comment by HighCommander4** [comment]
> To compare client::String you can compare the respective pointers.

Thanks. I find it a bit counterintuitive that a _pointer_ comparison in C++ code compares the _values_ of the strings, but I understand this may be a quirk of mapping C++ to JS.

I will leave the bug open to track adding the other String and Array APIs.

**Comment by alexp-sssup** [comment]
Missing APIs from client::String and client::Array are now available in current master.
