### ISSUE TITLE
Segfault when running opt with PreExecute on libstdlibs

### ISSUE THREAD

**Issue by cynecx** [leaningtech/cheerp-meta#26]
Hey,

I am currently trying to compile cheerp and everything went good so far. But when optimizing the standard libs I get a segmentation fault. Here is the log:

```
#0 0x561bc6860421 llvm::sys::PrintStackTrace(_IO_FILE*) (/opt/cheerp/bin/opt+0xa7a421)
#1 0x561bc685e449 SignalHandler(int) (/opt/cheerp/bin/opt+0xa78449)
#2 0x7f5e722ebe80 __restore_rt (/usr/lib/libpthread.so.0+0x10e80)
#3 0x561bc64eee03 llvm::GlobalValue::isDeclaration() const (/opt/cheerp/bin/opt+0x708e03)
#4 0x561bc696ba98 llvm::Interpreter::callFunction(llvm::Function*, std::vector<llvm::GenericValue, std::allocator<llvm::GenericValue> > const&) (/opt/cheerp/bin/opt+0xb85a98)
#5 0x561bc696c294 llvm::Interpreter::visitCallSite(llvm::CallSite) (/opt/cheerp/bin/opt+0xb86294)
#6 0x561bc696c9a2 llvm::Interpreter::run() (/opt/cheerp/bin/opt+0xb869a2)
#7 0x561bc695a765 llvm::Interpreter::runFunction(llvm::Function*, std::vector<llvm::GenericValue, std::allocator<llvm::GenericValue> > const&) (/opt/cheerp/bin/opt+0xb74765)
#8 0x561bc668ae46 cheerp::PreExecute::runOnModule(llvm::Module&) (/opt/cheerp/bin/opt+0x8a4e46)
#9 0x561bc65143a9 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/opt/cheerp/bin/opt+0x72e3a9)
#10 0x561bc5fd9d75 main (/opt/cheerp/bin/opt+0x1f3d75)
#11 0x7f5e714a7710 __libc_start_main (/usr/lib/libc.so.6+0x20710)
#12 0x561bc5fecab9 _start (/opt/cheerp/bin/opt+0x206ab9)
Stack dump:
0.  Program arguments: /opt/cheerp/bin/opt -O3 -PreExecute libstdlibs.full.bc -o libstdlibs.bc 
1.  Running pass 'CheerpPreExecute' on module 'libstdlibs.full.bc'.
[1]    5874 segmentation fault (core dumped)  /opt/cheerp/bin/opt -O3 -PreExecute libstdlibs.full.bc -o libstdlibs.b
```

EDIT:
I am using the upstream source not a tagged one.

**Comment by alexp-sssup** [comment]
Is the error reproducible every time? It would be probably useful if you could attach the libstdlibs.full.bc intermediate file.

**Comment by cynecx** [comment]
I renamed the file into a jpeg one because github didn't allow me to upload arbitrary files.

![libstdlibs full bc](https://cloud.githubusercontent.com/assets/5961244/14410338/a6ae957e-ff2d-11e5-9985-1879f5c53edd.jpeg)

**Comment by alexp-sssup** [comment]
I cannot reproduce the problem locally. Can you provide more details on your system? PreExecuter depends on some low level mmap calls, but that should not be a problem on modern linux systems.

**Comment by cynecx** [comment]
I am on Arch Linux.

Linux 4.5.0-1-cx2 #1 SMP PREEMPT x86_64 GNU/Linux.
g++ (GCC) 5.3.0

I tried to recompile everything but I am stil getting that particular error.
I maybe have a suspicion, are you compiling llvm/clang with clang or gcc? I don't have clang installed so cmake is instead using gcc.

**Comment by alexp-sssup** [comment]
We usually test building with both toolchain, so it should not be a compiler issue. Still it could be worth a shot to try building using clang.

**Comment by cynecx** [comment]
Yes! It worked.

I was actually right with my suspicion. This time I build cheerp-llvm with clang:
export CC=/usr/bin/clang
export CXX=/usr/bin/clang++

And I did all the usual stuff and finally came to the preexecution part. Surprisingly I didn't get any segfault! So it is probably gcc's fault.

I will try later GCC 6 to see if this is already fixed in upstream.

**Comment by alexp-sssup** [comment]
Thanks for the report, I will double check what version of gcc is being used on our build machines.
