### ISSUE TITLE
Issues with Boost?

### ISSUE THREAD

**Issue by cynecx** [leaningtech/cheerp-meta#30]
I would like to use Boost in my project but it doesn't seem that cheerp would support it.
For example, I am using a header only library (`boost::container::small_vector`) but cheerp can't compile it.
The error message is the following:

```
In file included from /opt/cheerp/include/boost/container/small_vector.hpp:27:
In file included from /opt/cheerp/include/boost/container/vector.hpp:27:
In file included from /opt/cheerp/include/boost/container/allocator_traits.hpp:32:
In file included from /opt/cheerp/include/boost/container/detail/mpl.hpp:26:
/opt/cheerp/include/boost/move/detail/type_traits.hpp:955:30: error: Cheerp: Field not supported in union
   ::boost::long_long_type   long_long_;
```

Is there any workaround?

**Comment by alexp-sssup** [comment]
I believe the problem happens in the max_align union, right? In Cheerp neither 64-bit integer not pointer are currently supported in unions, so you should comment them out of that structure. With Cheerp there are no alignment requirements anyway so this should not be a problem. Please note that boost implementations may do pointer manipulations that are not safe on Cheerp, so your mileage may vary.

**Comment by alexp-sssup** [comment]
As of Cheerp 2.0RC2 we recommend to use Wasm mode to compile like Boost
