### ISSUE TITLE
std::string concatenation broken

### ISSUE THREAD

**Issue by robson3** [leaningtech/cheerp-meta#32]
This code

```
#include <cheerp/clientlib.h>
#include <string>

void webMain()
{
    const auto text = "ABCDEFGHIJKLMNOPQRSTUVW" + std::to_string(2000 / 3.0);
    client::console.log(text.c_str());
}
```

outputs `ABCDEFGHIJK` to the console, this is clearly incorrect.

Surprisingly, almost identical code

```
#include <cheerp/clientlib.h>
#include <string>

void webMain()
{
    const auto text = "ABCDEFGHIJKLMNOPQRSTUVW" + std::to_string(2 / 3.0);
    client::console.log(text.c_str());
}
```

produces correct answer which is `ABCDEFGHIJKLMNOPQRSTUVW0.666667`

Compiled with Cheerp 1.2.1 on Windows and tested with Firefox 46.0.1

**Comment by alexp-sssup** [comment]
The issue is fixes in git master, a quick workaround for you would be to get the ```<string>``` header from the cheerp-libcxx repository.
