### ISSUE TITLE
Compile cheerp itself

### ISSUE THREAD

**Issue by piranna** [leaningtech/cheerp-meta#33]
Would it be possible to self-host cheerp compiling itself to Javascript and running it with Node.js, and ideally having it published as a `npm` package? I'm planning to use it on NodeOS as an alternative to GCC to install compiled modules from inside itself.

**Comment by alexp-sssup** [comment]
At the moment compiling cheerp to JS would be a major challenge. LLVM does not strictly follow the type safety requirements of the Web platform, in particular in its handling of IR. It's a project that I have been thinking about for a while, but at this stage it seems out of reach.

**Comment by piranna** [comment]
I'm not interested to use Cheerp on a web browser but on Node.js, but I understand there could be some limitations if the source C++ code (in that case LLVM itself) do some tricks like pointers arythmetic and so. Has been done any checks on this area, or has this been just an idea?

**Comment by alexp-sssup** [comment]
The same limitations for the Web platform applies to purely JS environments such as node. I know for sure that the way LLVM Values are linked to users is highly type unsafe. Most probably other code is problematic as well.

**Comment by jagenjo** [comment]
I would love to see cheerp.js one day...

**Comment by carlopi** [comment]
Hi @piranna & @jagenjo, loving the meta-idea, but I fear this is out of scope for the project in it's current form.

A somehow similar meta solution is a in-browser virtual machine that my colleagues have been building: https://webvm.io/.
It execute a Debian distro with a hosts of packages installed (node / python / ruby / etc)
Currently it allows for example to compile C/C++ with gcc or clang to native (and then execute the results) and it's in my todo-list to verify whether it can work with the Cheerp package installed.

Note that WebVM is currently distributed as browser-only, but this may change in the future.
