### ISSUE TITLE
Working with files

### ISSUE THREAD

**Issue by jannone** [leaningtech/cheerp-meta#34]
I want to convert a C program that takes a file as argument, process it, and generates another file as output, plus it generates some stderr messages in case of error.

It should run in the browser.

Some questions:

- How to input the file contents to the program?
- How to detect the end of the execution?
- How to capture the stderr messages?
- How to capture the file output contents?

The wiki says there is a way to plug events and such, but I couldn't find more information about it.

Thank you

**Comment by alexp-sssup** [comment]
In general there is no such a thing as "files" on the web platform. An approach would be to modify the code to accept a uint8_t* to the file contents instead of the file name. The output of stdout will be shown in the browser console by default.
