### ISSUE TITLE
regex fails to initialize when using `[]`

### ISSUE THREAD

**Issue by Plaristote** [leaningtech/cheerp-meta#38]
When initializing a regex which uses a pattern containing brackets, the generated code fails and claims there's an undefined value at line 3818 of the regex header.

The issue is easily reproducible:
```c++
#include <cheerp/client.h>
#include <cheerp/clientlib.h>
#include <regex>

void webMain()
{
  std::regex regexp("[a-z]");
}
```
This is using the 1.2.1 version.

**Comment by alexp-sssup** [comment]
The issue seems fixed in current master
