### ISSUE TITLE
When to support the compilation of wasm？

### ISSUE THREAD

**Issue by cncmd** [leaningtech/cheerp-meta#39]

**Comment by alexp-sssup** [comment]
We will support Web Assembly in full as soon the technology will be developed further to raise some of its current limitations.

The first revision of wasm which is being released in these months will have limitations in line to asm.js (emulated linear address space, fixed memory usage, no easy interoperability which browser API). This programming model is too limited to be used at the scale at which Cheerp is currently being used.

We will support wasm fully when such restriction are lifted and, in line with our commitment to FOSS and the Open Web, we plan to contribute to wasm development as we are currently doing with normal JS engines, in particular SpiderMonkey. Experimentally, we might also add support for web assembly at earlier stages, but we currently have no plan to do so.

There will be a post some time in the future in which we will detail among other things our support for Web Assembly, so please stay tuned.

**Comment by cncmd** [comment]
I am very honored to receive your reply, I very much like this technology, I would like to establish this technology in China in the community, the domain name(www.cheerp.cn) ready, please authorize me, follow your rights.
