### ISSUE TITLE
PPA support for trusty

### ISSUE THREAD

**Issue by kripken** [leaningtech/cheerp-meta#4]
After adding the PPA and reloading, I see the latest version of cheerp is 1.0-1. Is there a way to get 1.2 builds for Ubuntu, or do I need to build from source?

**Comment by alexp-sssup** [comment]
Hello Alon, you need to change the ubuntu repository from trusty or utopic to wily in the /etc/apt/sources.list.d configuration directory.

**Comment by kripken** [comment]
Thanks! Would that work even if I'm on Trusty, though?

**Comment by alexp-sssup** [comment]
I've quickly tested on a trusty docker and it seems that it won't work due to dependencies on newer libstdc++, we are currently doing a backported build, but it will take a few hours.

**Comment by alexp-sssup** [comment]
We have backported 1.2 to trusty on the PPA, please revert the apt configuration to us trusty again.

**Comment by kripken** [comment]
Thanks :)
