### ISSUE TITLE
Can not install Cheerp on Mac OS X Yosemite

### ISSUE THREAD

**Issue by uMaxmaxmaximus** [leaningtech/cheerp-meta#41]
![image](https://cloud.githubusercontent.com/assets/19378179/21607685/e338d70c-d1c8-11e6-8b0b-70eaad474afb.png)

`opt` directory is not exists

**Comment by alexp-sssup** [comment]
Please create the /opt directory before installing.

```sudo mkdir /opt```

**Comment by uMaxmaxmaximus** [comment]
I know, yet it is an issue, you do need to create the directory, if the user is absent. for this I created the ticket.
