### ISSUE TITLE
Disable name mangling of object members?

### ISSUE THREAD

**Issue by CrazyGuy108** [leaningtech/cheerp-meta#42]
I decided to look into how Cheerp 1.2.1 handles JS objects, so I wrote a little test program.

testobj.js:
```js
var test =
{
    x: 1
};
```
test.cpp:
```c++
#include <cheerp/client.h>
#include <cheerp/clientlib.h>

namespace client
{
	class Test
	{
	public:
		int x;
	};
	extern Test test;
}

void webMain()
{
	client::console.log(client::test.x);
}
```
test.html:
```html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<script src="testobj.js"></script>
		<script src="test.js"></script>
	</head>
</html>
```
I compiled test.cpp using `clang++ -O3 -nostdlib -target cheerp test.cpp -o test.js`.
When ran, the code outputted 0! Looking at test.js, I found the following code snippet (linebreaks+tabs added for readability):
```js
function c()
{
	var d=(test.i0>>0);
	var e=String(d>>0);
	console.log(e);
	return;
}
```
The compiled script seems to be accessing member `i0` of the `test` object! If I add a get() function in test.cpp and testobj.js, it runs just fine, printing 1, but it seems like an ugly workaround for some APIs that don't have accessor functions for every member. Is there a way to disable this and allow me to access object members directly instead of using a function?

**Comment by alexp-sssup** [comment]
No, there is no way to disable mangling on C++ side object. Using the same names for all objects reduces the number of internal VM maps that are generated on large programs. Moreover the compiler may reorder/reorganize the fields of an object to reduce the memory footprint. To pass JS object with predictable names to JS APIs I can suggest the following solution:

```
namespace client
{
    struct Coordinate: public Object
    {
        void set_x(int);
        void set_y(double);
    };
}
client::Coordinate* makeCoord(int x, double y)
{
    client::Coordinate* coord=(client::Coordinate*)new client::Object();
    coord->set_x(42);
    coord->set_y(0.2);
    return coord;
}
```

In the next release there will be some more flexible APIs, but the general requirement of mangling will persist.

**Comment by CrazyGuy108** [comment]
So the only workaround is using member functions. Got it, thanks.
