### ISSUE TITLE
String + String compile error

### ISSUE THREAD

**Issue by uMaxmaxmaximus** [leaningtech/cheerp-meta#45]
```C++
#include <cheerp/client.h>
using namespace client;

int webMain() {

    String hello("Hello");
    String name("World");
    String text(hello + name);
    alert(text);

    return 0;
}
```

compile to:
```javascript
"use strict";
/*Compiled using Cheerp (R) by Leaning Technologies Ltd*/
var aSlot = null;
var oSlot = 0;
var nullArray = [null];
var nullObj = {d: nullArray, o: 0};
function p() {
	var a = "Hello";
	var c = "World";
	var d = +a.valueOf();
	var b = +c.valueOf();
	var a = String((d + b));
	alert(a);
	return 0 >> 0;
}
function g(d, e) {
	var label = 0;
	var a = String();
	var b = (d[e >> 0 >> 0] & 255);
	if (!(((b & 255) === 0))) {
		var c = 0;
		while (1) {
			var q = String.fromCharCode(((b << 24) >> 24) >> 0);
			var a = a.concat(q);
			var c = ((c >> 0) + (1 >> 0) >> 0);
			var b = (d[(e >> 0) + (c >> 0) >> 0] & 255);
			if (((b & 255) === 0)) {
				break;
			}
		}
	}
	return String(a);
}
var h = new Uint8Array([72, 101, 108, 108, 111, 0]);
var i = new Uint8Array([87, 111, 114, 108, 100, 0]);
p();
```

Google closure compiler compile to:
```javascript
alert(String(+"Hello".valueOf()+ +"World".valueOf()));
```

BUT must be:
```javascript
alert("Hello"+"World");
```

**Comment by uMaxmaxmaximus** [comment]
String class not correct support + operator in  C++

**Comment by alexp-sssup** [comment]
std::string and client::String are very different and not interchangeable. It's also not obvious which is faster, it depends on the use case. For example probably in your example (string concatenation) client::String is faster, but probably it's faster to access std::string chars than using client::String::charCodeAt. Moreover client::String is an immutable type, while std::string is not.

Supporting the '+' operator is somehow complicated but possible. In the mean time you can use the equivalent client::String::concat member function. As a side note, it's on the other hand not possible to support the '+=' operation on String as the JavaScript one operates on the references instead on the String themselves (as they are immutable). This kind of operation as no mapping to C++.

**Comment by uMaxmaxmaximus** [comment]
You offer people inside the C++ world work with std::string, and the interaction with the browser, convert their client::String?

**Comment by alexp-sssup** [comment]
The best solution is to minimize the amount of conversion between the two. If you read something from an <input> element and this text will be put back in the DOM just keep everything in client::String. If the data comes from a complex C++ program or library and you want to pass it to the DOM, do the conversion at the very last moment. I hope I have answered your question.
