### ISSUE TITLE
Why name of main function is "webMain" instead of "main"?

### ISSUE THREAD

**Issue by uMaxmaxmaximus** [leaningtech/cheerp-meta#46]
Why name of main function is "webMain" instead of "main"?

**Comment by alexp-sssup** [comment]
This is explained here: https://github.com/leaningtech/cheerp-meta/wiki/Browser-side-programming-guide#the-webmain-entry-point

In brief, in a Web app you initialize your event handlers in webMain and then let the program run in an event-driven way, since that's how the Web platform is designed.
