### ISSUE TITLE
Class static props NOT EXPORTED to JS!!

### ISSUE THREAD

**Issue by uMaxmaxmaximus** [leaningtech/cheerp-meta#49]
Class static props NOT EXPORTED to JS!!

already two years....

**Comment by carlopi** [comment]
This has been fixed! I will be working also at the other [[cheerp::jsexport]] issues.
Static methods are jsexported and accessible via ClassName.methodName(args) in JavaScript.

Fields are out of the scope for jsexport, so static fiedls also, you will have to define the relevant (possibly static) getter and setters..

Here an article about jsexport that explain the roadmap a bit: https://medium.com/leaningtech/jsexport-cpp-in-the-browser-made-easy-710b2982046e.
