### ISSUE TITLE
Not optimized JS output

### ISSUE THREAD

**Issue by uMaxmaxmaximus** [leaningtech/cheerp-meta#50]
![image](https://cloud.githubusercontent.com/assets/19378179/22730755/4d18bd6c-edf9-11e6-9108-d48131cf1c72.png)

compile to:
![image](https://cloud.githubusercontent.com/assets/19378179/22730859/ad1318d4-edf9-11e6-897a-7f0958d1e482.png)

C++ Cat constructor is empty, but in 6 line is called.
And overall output contains many unused items.
I realize this is very little overhead, but it would be nice to remove.

**Comment by uMaxmaxmaximus** [comment]
C++ code
![image](https://cloud.githubusercontent.com/assets/19378179/22731258/0e99cc1e-edfb-11e6-8fbd-631328fb5146.png)

JS output code
![image](https://cloud.githubusercontent.com/assets/19378179/22731274/14f82c18-edfb-11e6-8005-ba32a718c45e.png)

Must be:
![image](https://cloud.githubusercontent.com/assets/19378179/22731306/31ade51e-edfb-11e6-852b-ed340cebe70b.png)

**Comment by uMaxmaxmaximus** [comment]
![image](https://cloud.githubusercontent.com/assets/19378179/22777063/1ecbd190-eec3-11e6-8163-00d97f2df7db.png)

Must be:
![image](https://cloud.githubusercontent.com/assets/19378179/22777129/516374c8-eec3-11e6-91f1-b3045feae791.png)

**Comment by carlopi** [comment]
Hi @uMaxmaxmaximus, thanks for your contribution, I did take some time to review this various items and connected idea and I am incline to close this issue as out of scope for the Cheerp compiler.

While there is a value in identifying possible improvements, and this ideas have been noted down, things like initialization of variables mostly count in smallish function and I doubt this to have significant impact in more complex cases.
