### ISSUE TITLE
Object::set_() error

### ISSUE THREAD

**Issue by uMaxmaxmaximus** [leaningtech/cheerp-meta#55]
```C++
Object *obj = new Object();

obj->set_("prop", 11); // ERROR
obj->set_("prop", "string"); // ERROR
obj->set_("prop", new String("string")); // ERROR
obj->set_("prop", new Number(1)); // ERROR
```

```C++
Function->prototype.set_("method", Callback([]{ })) // ERROR
```

**Comment by alexp-sssup** [comment]
Please try again with the just released 1.3 version. new String/Callback are now properly supported. The first two cases can be supported but I am not sure if it's a good idea or not. The Number issue is still a bug and will be fixed.

**Comment by uMaxmaxmaximus** [comment]
omg 1.3 released)!! aeah

**Comment by uMaxmaxmaximus** [comment]
I think, or compilation speed is incredibly increased?

**Comment by alexp-sssup** [comment]
I am not sure about how to read this message. Do you think that 1.3 is slower or faster than 1.2.1?

**Comment by uMaxmaxmaximus** [comment]
sory im from russian ans use google translator. i mean 1.3 very very very faster then 1.2.1
