### ISSUE TITLE
Avoid polluting the global scope by placing compiler output into an IIFE

### ISSUE THREAD

**Issue by jbmonroe** [leaningtech/cheerp-meta#6]
It's possible that the compiled C++ code included in a page might not be the only included JS file.  Right now the output of the compiler pollutes the global name space with a lot of single-letter function names that would best be gathered inside an Immediately-Invoked Function Expression (IIIFE).  This is particularly important since the "use strict" pragma is applied globally to all scripts which follow the inclusion on the page instead of being restricted to just the Cheerp-generated code.

At some point perhaps Cheerp will generate E6 modules, but until then, IIFEs are a good solution to this (IMHO--YMMV).

**Comment by alexp-sssup** [comment]
Cheerp 1.2 has a command line option that should do what you ask: -cheerp-make-module

**Comment by alexp-sssup** [comment]
Please re-open this bug if the -cheerp-make-module option is not suitable for your needs
