### ISSUE TITLE
Wrong readme for macOS

### ISSUE THREAD

**Issue by uMaxmaxmaximus** [leaningtech/cheerp-meta#60]
in cheerp folder we have `readme`:

```
Installation
------------------------------------------
Currently Cheerp needs to be unpacked in /opt/cheerp/
```

but in `cheerp/share/cmake/Modules/CheerpToolchain.cmake` file we have another path

```
INCLUDE(CMakeForceCompiler)
list(APPEND CMAKE_MODULE_PATH "/Applications/cheerp/share/cmake/Modules")
```

just fix mac os readme
=========

**Comment by alexp-sssup** [comment]
The /opt/cheerp/ requirement is indeed obsolete. The instructions has been made updated in current master.
