### ISSUE TITLE
Can cheerp be used to write react components

### ISSUE THREAD

**Issue by fbunn** [leaningtech/cheerp-meta#61]
The 'render' method in JSX needs to return free form text that may contain JavaScript. It is a DECLARATIVE style of coding.

There's no need to access the DOM. ReactJs framework does that and calls each control in a DOM element to render only the contents of the DOM element.

To do this, I believe there has to be some kind of preprocessor feature to mark the enclosed text as JavaScript

**Comment by alexp-sssup** [comment]
Could you please provide an example output of Cheerp and how it should be modified to achieve what you are saying?
