### ISSUE TITLE
How can I get the character buffer from a client::String, eg. to pass it to client::console.log()?

### ISSUE THREAD

**Issue by occultations** [leaningtech/cheerp-meta#62]

**Comment by alexp-sssup** [comment]
You can pass a client::String directly to console::log. Can you add more details on what you are trying to achieve?

**Comment by occultations** [comment]
I tried passing a client::String to console::log(), but the output was blank.  Here's my code:
            client::String a("aaa");
            client::String s;
            s = a;
            client::console.log("s vvv");
            client::console.log(s);
            client::console.log("s ^^^");
And here is the output:
17:41:31.317 s vvv  example.js:1:3751
17:41:31.317   example.js:1:3766
17:41:31.318 s ^^^  example.js:1:3791

**Comment by alexp-sssup** [comment]
It is incorrect to use client::String as values. Try:

client::String* a=new client::String("aaa");
client::String* s;

All JS objects must be used as pointers in C++ code.

**Comment by occultations** [comment]
Thanks for your quick answers.  But I don't understand what you mean by "It is incorrect to use client::String as values".  Surely a variable of type client::String has a value?  And I don't understand what you mean by "All JS objects must be used as pointers in C++ code."  Am I not allowed to have variables in my C++ code that are instances of classes/structs/unions?

**Comment by alexp-sssup** [comment]
I apologize for being unclear. You are fully allowed to use classes/structs/unions in your C++ code. What I meant is that all browser provided types, which are contained in the ```client``` namespace (client::String is one example), can only ever be used as pointers, references or const references. So for example, all the following code is allowed:

```c++
int func(client::String* str);
int func(client::String& str);
int func(const client::String& str);
client::String* func(int);
client::String& func(int);
struct A
{
    client::String* str1;
    client::XMLHttpRequest* xhr;
};
```

Please consider it as an not-exhaustive list. Pointers/references to client objects can be used like you would use any other pointer or reference.

On the other hand the following code is not allowed
```c++
// Parameter passed by copy
int func(client::String str);
// Return value passed by copy
client::String func(int);
// client objects cannot be contained  directly in a struct
struct
{
    client::String str;
    client::XMLHttpRequest xhr;
};
```

**Comment by occultations** [comment]
Thank you for those examples of what is and isn't allowed, they help explain some of the things I couldn't get to work.  I'm new to cheerp, I found it last week when I googled "C++ to javascript conversion".  Is there some documentation somewhere saying what is and isn't allowed in cheerp?

**Comment by alexp-sssup** [comment]
Our wiki is a good place to start

http://wiki.leaningtech.com

In particular you may find these interesting:
https://github.com/leaningtech/cheerp-meta/wiki/Getting-started
https://github.com/leaningtech/cheerp-meta/wiki/Browser-side-programming-guide
