### ISSUE TITLE
Cannot use unicode escape sequences in string literals

### ISSUE THREAD

**Issue by jonathanmcdougall** [leaningtech/cheerp-meta#64]
This:

    "\u2014"

generates that:

    "\xe2\x80\x93"

which are actually three 16-bit characters, since JavaScript is UCS-2. The `\u` escape sequences should be output verbatim.

**Comment by smvv** [comment]
The clang C++ frontend will convert the utf-8 encoded string to 8-bit literals.
To get 32-bit characters, it is possible to use:

```cpp
std::wstring foo = L"\u2014";
```

This will result in the following JS code:
```javascript
LretConstructor5=new Int32Array(4);
LretConstructor5[0]=8212;          // hex(8212) = 0x2014
LretConstructor5[1]=0;             
```

**Comment by jonathanmcdougall** [comment]
Fair enough. I was expecting cheerp to convert UTF-8 strings, but I can understand if it doesn't. Can you add something to [the wiki](https://github.com/leaningtech/cheerp-meta/wiki/Browser-side-programming-guide#using-dom-strings) when you have a minute?

There's also a problem with `String::fromCharPtr`: it's using [`fromCharCode()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/fromCharCode) instead of [`fromCodePoint()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/fromCodePoint), so that surrogate pairs (`L"\U0001F44D"` for example) don't work. That's a simple fix, and there's a polyfill on MDN that can be used instead.

**Comment by alexp-sssup** [comment]
Cheerp now defines a ```client::String::fromUtf8``` method to correctly converted UTF-8 strings to JS strings. Closing.
