### ISSUE TITLE
Bad codegen with static const member variables initialized inline

### ISSUE THREAD

**Issue by jonathanmcdougall** [leaningtech/cheerp-meta#65]
When a const member variable is initialized inline and passed at least once to a function taking a const reference, the corresponding JavaScript variable is left undefined.

    > clang++ --version
    Cheerp 1.3 clang version 3.7.0 (https://github.com/leaningtech/cheerp-clang.git d481cf2213eb438136881142b4e48accd9989882) (https://github.com/leaningtech/cheerp-llvm.git 41eafb50350ed3e74200a1cb91f00791e3b06588) (based on LLVM 3.7.0svn)
    Target: i686-pc-windows-gnu
    Thread model: posix

    > cat test.cpp
    struct S { static const int i = 3; };
    
    void f(const int& t);
    
    void webMain()
    {
    	f(S::i);
    }

    > clang++ -target cheerp -cheerp-pretty-code test.cpp

    > cat a.out
    "use strict";
    /*Compiled using Cheerp (R) by Leaning Technologies Ltd*/
    var aSlot=null;var oSlot=0;var nullArray=[null];var nullObj={d:nullArray,o:0};
    function __Z7webMainv(){
    	__Z1fRKi(__ZN1S1iE);
    	return;
    }
    var __ZN1S1iE;
    __Z7webMainv();

Note that `__ZN1S1iE` is left undefined.

Workarounds:

 1. Initialize the constant outside the class;
 2. Never get a const reference to it.

**Comment by smvv** [comment]
It is not possible to initialize the constant inside the class. That will result in multiple definitions when the class is included across multiple files.

The following code will fix your issue:
```
struct S { static const int i; };
const int S::i = 3;

void f(const int& t);

void webMain()
{
        f(S::i);
}
```

Note that your code does also not work with a C++ to x86 compiler: http://cpp.sh/2jtwk (see the undefined reference to `S::i`). We will add an error to Cheerp to notify the user that there is an undefined reference to `S::i`, to avoid having a runtime error in JavaScript.

**Comment by jonathanmcdougall** [comment]
Right, okay. I think I understand what's going on.

> It is not possible to initialize the constant inside the class

This is actually incorrect. You _can_ initialize the constant, but you need to add an out-of-class definition if it is odr-used, such as by binding it to a reference (by calling `f()` above) or taking its address. This has been the case since C++98, afaik.

    struct S { static const int i = 3; };
    const int S::i;
    
    void f(const int& t);
    
    void webMain()
    {
    	f(S::i);
    }

generates:

    "use strict";
    /*Compiled using Cheerp (R) by Leaning Technologies Ltd*/
    var aSlot=null;var oSlot=0;var nullArray=[null];var nullObj={d:nullArray,o:0};
    function __Z7webMainv(){
    	__Z1fRKi(__ZN1S1iE);
    	return;
    }
    var __ZN1S1iE=3;
    __Z7webMainv();

which is fine.

If the constant is not odr-used, then a definition is not necessary, which is why I had to use a const reference to reproduce the issue. In this case, cheerp will happily use the literal and won't generate a unnecessary variable for it. I'm not sure whether that's you being smart in codegen, or if clang/llvm is doing the work for you ;)

What made this difficult for me to understand and reproduce is that Visual C++ seems to generate a weak definition automatically so that the definition of `S::i` is not actually required at all. This is what made me file this bug report. I should have checked with other compilers. You are correct that the code is ill-formed and both clang++ and g++ reject it.

> We will add an error to Cheerp to notify the user that there is an undefined reference to S::i, to avoid having a runtime error in JavaScript.

Nice.

As an aside, have you thought of requiring a definition for everything unless marked with some attribute? You have a `[[cheerp::jsexport]]`, but it would be nice to have _all_ definitions be required unless marked with `[[cheerp::jsimport]]` or something.
