### ISSUE TITLE
Excessive null checks during conversions with optimizations

### ISSUE THREAD

**Issue by jonathanmcdougall** [leaningtech/cheerp-meta#66]
> clang++ --version
    Cheerp 1.3 clang version 3.7.0 (https://github.com/leaningtech/cheerp-clang.git d481cf2213eb438136881142b4e48accd9989882) (https://github.com/leaningtech/cheerp-llvm.git 41eafb50350ed3e74200a1cb91f00791e3b06588) (based on LLVM 3.7.0svn)
    Target: i686-pc-windows-gnu
    Thread model: posix

    > cat test.cpp
    struct A     {};
    struct B : A {};
    struct C : B {};
    struct D : C {};
    struct E : D {};
    
    void a(A* p);
    void b(B* p)  { a(p); }
    void c(C* p)  { b(p); }
    void d(D* p)  { c(p); }
    void e(E* p)  { d(p); }
    
    E* make_e();
    
    void webMain()
    {
        e(make_e());
    }

    > clang++ -target cheerp -cheerp-pretty-code -O2 test.cpp

    > cat a.out
    "use strict";
    /*Compiled using Cheerp (R) by Leaning Technologies Ltd*/
    var aSlot=null;var oSlot=0;var nullArray=[null];var nullObj={d:nullArray,o:0};
    function __Z7webMainv(){
    	var tmp0=null;
    	tmp0=__Z6make_ev();
    	__Z1aP1A(((tmp0===null)||((tmp0===null)||((tmp0===null)||(tmp0===null)))?null:tmp0));
    	return;
    }
    __Z7webMainv();

The more conversion you do, the more checks you get.

**Comment by smvv** [comment]
@jonathanmcdougall what compiler flags and compiler version are you using to compile the code?

When I compile the code using `~/work/cheerp/opt/bin/clang++ -target cheerp -cheerp-pretty-code -o cast-null-checks.js cast-null-checks.cpp` (using the master branch), I get:

```
"use strict";
/*Compiled using Cheerp (R) by Leaning Technologies Ltd*/
var __imul=Math.imul;
var __fround=Math.fround;
var aSlot=null;var oSlot=0;var nullArray=[null];var nullObj={d:nullArray,o:0};
function __Z7webMainv(){
        var Lcall=null;
        Lcall=__Z3divv();
        __Z1aPN6client6ObjectE(Lcall);
        return;
}
__Z7webMainv();
```

**Comment by jonathanmcdougall** [comment]
This only seems to happen with `-O2` or `-O3`.

    c:\cheerp\bin\clang++ -target cheerp -cheerp-pretty-code -O2 test.cpp

**Comment by smvv** [comment]
Thanks for the information. I've pushed a commit to master that fixes the unnecessary null checks: https://github.com/leaningtech/cheerp-clang/commit/1efad6a9b81e2c3f415dc34019a550ee06097d37
