### ISSUE TITLE
Cannot generate WASM output

### ISSUE THREAD

**Issue by opiepj** [leaningtech/cheerp-meta#69]
Getting an error when generating a wasm file, I'm able to run the example normally, but getting the error: `/opt/cheerp/bin/llc: error: invalid target 'cheerp-wasm'.`, any ideas?

**Script**:
```bash
/opt/cheerp/bin/clang++ \
  -target cheerp \
  -cheerp-mode=wasm \
  -cheerp-linear-heap-size=128 \
  -cheerp-wasm-loader=loader.js \
  -o output.wasm \
  input.cpp
```

**input.cpp**
```c++
// The cheerp/clientlib.h header contains declarations
// for all the browser APIs.
#include <cheerp/clientlib.h>

// webMain is the entry point for web applications written in Cheerp.
void webMain()
{
    // client is a C++ namespace that contains all browser APIs
    client::console.log("Hello World Wide Web!");
}
```

**Error**: `/opt/cheerp/bin/llc: error: invalid target 'cheerp-wasm'.`

**Comment by alexp-sssup** [comment]
What version of Cheerp are you using? What is the output of ```/opt/cheerp/bin/clang++ -v```

**Comment by opiepj** [comment]
`/opt/cheerp/bin/clang++ -v`
returns
```
clang version 3.7.0 (https://github.com/leaningtech/cheerp-clang 9652dc3b2af58d596f25e7efa37d8b57ac76bd85) (https://github.com/leaningtech/cheerp-llvm 93c57b0ab9a9c9dca48c80ce5e6dab0aeb605a13)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
```

**Comment by alexp-sssup** [comment]
Did you built from source? if so you need to enable CheerpWastBackend in the CMake configuration. We have updated the build instructions to reflect this: https://github.com/leaningtech/cheerp-meta/wiki/Linux-build-instructions#build-cheerp-llvmclang-based-compiler

Moreover, you won't be able to use ```client::console.log``` from wasm code. In the final release this will be forbidden at compile time, but at this stage the compiler is not yet checking this. Please take a look here: https://github.com/leaningtech/cheerp-meta/wiki/WebAssembly-output-(wasm-or-wast-mode)#using-dom-apis

**Comment by opiepj** [comment]
Alright let me give it another shot.

**Comment by opiepj** [comment]
Hey go it working, thank you @alexp-sssup !
