### ISSUE TITLE
Problems during build/install of 'Cheerp LLVM/clang based compiler'

### ISSUE THREAD

**Issue by johanax** [leaningtech/cheerp-meta#72]
Hi,
during build/install of 'Cheerp LLVM/clang based compiler' on a Linux machine I get the following error messages:

make install
.
.
.
-- Installing: /opt/cheerp/lib/libclangStaticAnalyzerFrontend.a
-- Installing: /opt/cheerp/lib/libclangFormat.a
-- Installing: /opt/cheerp/bin/clang-3.7
CMake Error at tools/clang/tools/driver/cmake_install.cmake:36 (file):
  file INSTALL cannot copy file
  "/root/cheerp/cheerp-llvm/build/bin/clang-3.7" to
  "/opt/cheerp/bin/clang-3.7".
Call Stack (most recent call first):
  tools/clang/tools/cmake_install.cmake:38 (include)
  tools/clang/cmake_install.cmake:55 (include)
  tools/cmake_install.cmake:73 (include)
  cmake_install.cmake:61 (include)

Makefile:104: recipe for target 'install' failed
make: *** [install] Error 1

Regards Johan

**Comment by alexp-sssup** [comment]
Hello, this seems to be either a permission issue or a disk space issue. Please check that you have the right permissions to copy the ```clang-3.7``` executable to ```/opt/cheerp/bin/``` and that there is enough disk space to do so.

**Comment by johanax** [comment]
Thanks,
there was not enough disk space :/)

Regards Johan
