### ISSUE TITLE
No package for Ubuntu 17.10 (Artful) ?

### ISSUE THREAD

**Issue by sasq64** [leaningtech/cheerp-meta#73]
```
E: The repository 'http://ppa.launchpad.net/leaningtech-dev/cheerp-ppa/ubuntu artful Release' does not have a Release file.
```

**Comment by alexp-sssup** [comment]
We will look into this, in the mean time you can try using the packages for xenial, they may work fine.

**Comment by alexp-sssup** [comment]
Nightly packages (https://launchpad.net/~leaningtech-dev/+archive/ubuntu/cheerp-nightly-ppa) are now built for artful. Future releases will be for artful as well.
