### ISSUE TITLE
Bridging "glue" code doesn't seem to be generated right

### ISSUE THREAD

**Issue by yyyc514** [leaningtech/cheerp-meta#74]
I'm using the 2.0RC1 compiler.  I'm using a pretty much stock JsBridge example (from https://github.com/leaningtech/cheerp-meta/wiki/Cheerp-Tutorial) but I changed the annotation to `[[cheerp::jsexport]]` as seems to be required now.  

I'm compiling with:

```
/Applications/cheerp/bin/clang++ -target cheerp -cheerp-mode=wasm -cheerp-wasm-loader=example.js -o0 -o example.wasm example.cpp -cheerp-pretty-code -cheerp-no-lto
```

Though I've tried various options, none of them working.

The JS generated is:

```
"use strict";
/*Compiled using Cheerp (R) by Leaning Technologies Ltd*/
function JsBridge(){
	this.i0=0;
	;
	this.d=[this];
	__ZN8JsBridgeC1Ev({d:this.d,o:0});
}
JsBridge.prototype.addAndReturn=function (a0){
	return __ZN8JsBridge12addAndReturnEi({d:this.d,o:0},a0);
};
var aSlot=null;var oSlot=0;var nullArray=[null];var nullObj={d:nullArray,o:0};
function fetchBuffer(path) {
	var bytes = null;
	if (typeof window === 'undefined' && typeof require === 'undefined') {
		bytes = new Promise( (resolve, reject) => {
			resolve(read(path,'binary'));
		});
	} else if (typeof window === 'undefined') {
		var fs = require('fs');
		bytes = new Promise( (resolve, reject) => {
			fs.readFile(path, function(error, data) {
				if(error) reject(error);
				else resolve(data);
			});
		});
	} else {
		bytes = fetch(path).then(response => response.arrayBuffer());
	}
	return bytes;
}
var HEAP8=null;
var HEAP16=null;
var HEAP32=null;
var HEAPF32=null;
var HEAPF64=null;
var __asm=null;
function __dummy() { throw new Error('this should be unreachable'); };
var importObject = { imports: {
	}};
fetchBuffer('example.wasm').then(bytes => WebAssembly.compile(bytes)
.then(m => new WebAssembly.Instance(m, importObject),console.log)
,console.log).then(instance => {
	HEAP8=new Uint8Array(instance.exports.memory.buffer);
	HEAP16=new Uint16Array(instance.exports.memory.buffer);
	HEAP32=new Int32Array(instance.exports.memory.buffer);
	HEAPF32=new Float32Array(instance.exports.memory.buffer);
	HEAPF64=new Float64Array(instance.exports.memory.buffer);
	__asm=instance.exports;
	instance.exports.__Z7webMainv();
},console.log).catch(console.log);
```

The error I get is: `ReferenceError: Can't find variable: __ZN8JsBridgeC1Ev`

The generated wast: 
```
(module
(type $vt_v (func ))
(type $vt_vi (func (param i32)))
(type $vt_iii (func (param i32 i32)(result i32)))
(type $vt_iiii (func (param i32 i32 i32)(result i32)))
(table anyfunc (elem $__wasm_nullptr $_ZN8JsBridgeC1Ev $_ZN8JsBridge12addAndReturnEi))
(memory (export "memory") 16 16)
(global (mut i32) (i32.const 1048576))
(func $__wasm_nullptr (export "___wasm_nullptr")
(local i32)
unreachable
)
(func $_ZN8JsBridgeC1Ev (export "__ZN8JsBridgeC1Ev")(param i32)
(local i32)
get_local 0
i32.const 0
i32.store align=4
)
(func $_ZN8JsBridge12addAndReturnEi (export "__ZN8JsBridge12addAndReturnEi")(param i32 i32)(result i32)
(local i32 i32)
get_local 0
i32.load align=4
set_local 3
get_local 0
get_local 3
get_local 1
i32.add
i32.store align=4
get_local 0
i32.load align=4
)
(func $_Z7webMainv (export "__Z7webMainv")
(local i32)
)
(func $memcpy (export "_memcpy")(param i32 i32 i32)(result i32)
(local i32 i32 i32 i32 i32)
get_local 2
i32.const 0
i32.eq
if
get_local 0
return
end
get_local 2
set_local 6
get_local 0
set_local 5
get_local 1
set_local 4
loop
block
get_local 6
i32.const -1
i32.add
set_local 6
get_local 4
i32.load8_u
set_local 7
get_local 5
get_local 7
i32.store8
get_local 6
i32.const 0
i32.eq
  if
br 1
    else
get_local 5
i32.const 1
i32.add
set_local 5
get_local 4
i32.const 1
i32.add
set_local 4
  end
i32.const 0
br 1
end
end
get_local 0
)
)
```

It seems to have the export annotations, yet by the time it gets to the browser `instance.exports` doesn't even mention them.  Am I doing something wrong?

**Comment by yyyc514** [comment]
I've tried Firefox, Safari, and Chrome.  They all seem to understand the .wasm (judging from developer tools) but some glue is still missing somewhere.  It's like the exports are getting lost or some part of the JS that should be generated is not being generated.

**Comment by yyyc514** [comment]
<img width="487" alt="screen shot 2017-12-20 at 6 01 43 pm" src="https://user-images.githubusercontent.com/6473/34232770-dea4e1d0-e5af-11e7-996d-9350e60f8abb.png">

**Comment by yyyc514** [comment]
If I compile to WAST (vs WASM) and then use `wast2wasm` to do the final compile step then the exports are properly present in the `.wasm` file but of course the `__asm` glue code is still missing from the emitted javascript.

**Comment by yyyc514** [comment]
Also out of curiosity if the entire JS "loader" is pre-generated why are stubs emitted instead of just say `__asm.__ZN8JsBridgeC1Ev({d:this.d,o:0});`?  I ask because the pong example has stubs like:

```
function V() {
  __asm.V();
}
```

**Comment by alexp-sssup** [comment]
js-exporting wasm classes is not supported. It is conceptually problematic since js-exported classes are supposed to be garbage collectible, but wasm memory must be allocated and deallocated from the linear memory heap. Beside this there is an additional issue: The initialization of wasm module is async. In current master every js-exported classe has a ```promise``` property that can be used to know when everything is properly loaded. This feature was added after RC1, and it will be available in the RC2 packages.

**Comment by yyyc514** [comment]
>Beside this there is an additional issue: The initialization of wasm module is async. 

That's not really that big a deal since the code itself could easily just check for that first, right?  The memory management is really the big blocker, yes?

**Comment by alexp-sssup** [comment]
The issue of async initialization is only a problem in the current RC1 release. The next RC and current git master already provide a ```promise``` member for every js-exported class and function. You can wait on the promise to know when the code is ready.

The general issue of memory management of js-exported objects can also easily be worked around. You should only js-export classes compiled to vanilla JS (i.e. using the [[cheerp::genericjs]] tag). That class will be compiled to plain, garbage collectible JS and you can use from JS without any problem.

Inside that class you are free to implement any logic, including allocating objects in wasm-mode. You need to be careful about properly managing the lifetime of the memory, for example you will need a ```release``` method in your js-export class to free all resources and avoid wasm-mode memory leaks.

**Comment by alexp-sssup** [comment]
Cheerp master (and nightly builds) now correctly diagnose that ````[[cheerp::jsexport]]``` can't be used on Wasm code. The following error messages will be emitted:
```
example.cpp:9:1: error: Cheerp: Attribute 'wasm' is incompatible with attribute 'jsexport'
class [[cheerp::jsexport]] JsBridge
^
example.cpp:21:17: error: Cheerp: Method 'log' of object console of non-wasm type 'client::Console' cannot be called in the wasm section
        console.log("Called C++ code");
                ^
2 errors generated.
```
