### ISSUE TITLE
Comparing Cheerp startup time to Emscripten

### ISSUE THREAD

**Issue by kripken** [leaningtech/cheerp-meta#8]
I've tried to reproduce the startup measurements on [the Cheerp 1.2 blogpost](http://blog.leaningtech.com/2016/02/cheerp-12-c-to-javascript-with-faster.html), but have not succeeded. Perhaps I do not understand what you mean specifically by "startup" - how did you define it?

I tried the following: I made a small C++ file that does almost nothing in main (like a printf). I then built that in Emscripten and Cheerp with -O3 (I also tried PreExecute on Cheerp, but it did not affect results). I measured both just parsing (in the SpiderMonkey shell) and execution in (SpiderMonkey and node.js). The numbers were similar between parsing and execution, which makes sense since in such a program almost all time is spent in parsing. Cheerp is generally faster to start up, up to 2x faster depending on the JS engine and how I measured, but not anywhere near the 10x factor I was looking for. In the browser environment, there is more noise since there is a webserver as well, but I get overall similar results, in both Firefox and Chrome.

The blogpost mentions, aside from the 10x factor, that it takes Cheerp output less than 3ms to start up on average. That by itself tells me we are probably defining "startup" differently, as that is surprisingly low for how I measured things. For example, it takes the SpiderMonkey shell 15ms for pure parsing of fannkuch compiled by Cheerp. This is on different machines, of course, but a factor of 5x is still very surprising since I'm on a decent machine, and CPU speed differences aren't that big these days. And also that's just pure parsing, not the rest of startup.

I guess we mean different things by "startup", and in my attempts I am just doing something different than you. If you can explain in detail how you got those numbers I'd be very grateful - if Emscripten has 10x slower startup in some sense, it clearly means Emscripten needs to fix something there :)

Sorry for wasting your time if I've missed something obvious here.

**Comment by smvv** [comment]
Hi Alon,

Below I've attached the patches that we applied on Emscripten master and fastcomp master. The file emscripten-time-to-main.patch adds a small line to the generated main() that records the time when that line is hit. Depending on what environment is used, _performance_now aliases dateNow, performance.now or (new Date()).getTime. The value obtained is written to the end of HEAP32[0]. When main() is finished, the value written to the end of HEAP32 is read and used to compute the difference in time with the value stored during the first executed line.

In short, we measure the time from the first executed line till the first executed line in main(). How did you measure the time?

If you want to emit time-to-main code for Cheerp, you can use "-mllvm -cheerp-measure-time-to-main". The file script-measure-time-to-main.patch adds a script to measure the time-to-main for Emscripten and Cheerp on v8 and SpiderMonkey.

[time-to-main-patches.zip](https://github.com/leaningtech/cheerp-meta/files/121576/time-to-main-patches.zip)

[0] This is a bit hacky but was easier to do than creating some space in that typed array and storing the value.

**Comment by kripken** [comment]
> In short, we measure the time from the first executed line till the first executed line in main().

I see, thank you. So first executed line in the same file, til main(). That explains a lot - I can see 3ms for Cheerp Fannkuch now too.

However, I'm not sure this is measuring what you want:

1. You're measuring *after* the JS engine loads, parses, and baseline-compiles etc. the script. Loading to some extent depends on the network etc., so maybe you want to ignore it here, but parsing and other JS compilation operations are quite significant, for example, as mentioned earlier Cheerp Fannkuch takes 15ms just to parse, which is already 5x more than the 3ms you reported. So that 3ms measurement ignores the bulk of startup time.
2. The Emscripten benchmark suite is not necessarily the best thing for this. It sets flags that make it easier to compare between JS VMs and Emscripten builds, but some of those are not normally good to set. For example, around half of your startup time measurement for Bullet is due to not having the mem init file optimization enabled. (The benchmark script disables it because it doesn't work in the d8 shell.) It also enables float32 optimizations which can slow down startup, etc.
3. Given that you *aren't* measuring parsing, asm.js should always be faster, since (on Firefox and Edge, and soon Chrome) it's compiled AOT during parsing, that is, before the script starts to run. And the rest of what you measure for startup is either identical between asm.js and non-asm.js, or asm.js should be faster (on compiled code). Yet you report a huge 3x slowdown for asm.js, so something definitely doesn't make sense to me yet. In other words: It was reasonable to think asm.js would start up more slowly, thinking of startup in general. But if you measure startup *after* parse, than the opposite is expected.

Meanwhile I looked into why Cheerp still starts up faster on small programs. Looks like most of the difference was starting up the Emscripten virtual filesystem, which I see you disabled in your patches, but I didn't when I measured ;) That's definitely something Emscripten should do better, so I finished up a pull request I had for it. After that, both take less than 10ms. Which makes sense - both Emscripten and Cheerp do almost nothing during startup, in a small program.

> How did you measure the time?

As I said above, I measured both just parsing of a program (in SpiderMonkey you can run `parse()` for that directly, etc.), and of running a program which has an essentially empty main so that it spends almost all the time starting up. I tried it both in the shells, and in the browser, where I also tried noting the start time in an earlier script tag (so it doesn't happen after parse). When main is essentially empty, then most time spent should be startup, and measuring it in separate script tags is fairly reliable, e.g.

````
<script>
var startTime = Date.now();
</script>

<script src="program.js"></script>

<script>
console.log('time: ' + (Date.now() - startTime) + ' ms');
</script>
````

Each method has some limitations of course, but in all of those I got generally similar results: With the filesystem disabled, as Emscripten now does, total startup time is similar between Emscripten and Cheerp. Cheerp is faster at startup minus parse, while Emscripten is faster when taking the total startup time into account (running an essentially empty main).

But that's for small programs. The largest benchmark you tested, Bullet, is still quite small compared to really big projects. It does start to show the issues, like the mem init optimization becomes more crucial for Emscripten, etc. But it would be nice to see more medium sized programs (like Lua, SQLite, etc.) as well as large ones (Poppler, Cube 2, etc.). On really big programs, startup and the first few frames of execution (JIT warmup) can take several seconds, and for different reasons than small ones (i.e. it's not the same as small ones scaled up, in my experience). For example, network access starts to matter, so it's useful to download binary components in parallel with the main script, etc.

Perhaps it might be interesting to see something like the [Massive](http://kripken.github.io/Massive/#faq-why_make_a_new_benchmark) benchmark ported to Cheerp? It has Poppler there, which is pretty big. It also measures startup in a few ways, each with its limitations, but I think overall they give a useful picture. Or, happy to collaborate on some new benchmark together.
