### ISSUE TITLE
Problems using std::unordered_map with enum class as key

### ISSUE THREAD

**Issue by johanax** [leaningtech/cheerp-meta#82]
Minimal example:
     enum class DimId {eNone=100, eTest};
     std::map<DimId, int> mMap;                    // OK
    std::unordered_map<DimId, int> mMap;  // Not OK

Output:

In file included from /opt/cheerp/bin/../include/c++/v1/__tuple:16:
/opt/cheerp/bin/../include/c++/v1/type_traits:990:38: error: implicit instantiation of undefined
      template 'std::hash<DimId>'
    : public integral_constant<bool, __is_empty(_Tp)> {};
                                     ^
/opt/cheerp/bin/../include/c++/v1/unordered_map:365:18: note: in instantiation of template class
      'std::is_empty<std::hash<DimId> >' requested here
          bool = is_empty<_Hash>::value && !__libcpp_is_final<_Hash>::value
                 ^
/opt/cheerp/bin/../include/c++/v1/unordered_map:747:13: note: in instantiation of default argument
      for '__unordered_map_hasher<DimId, std::__hash_value_type<DimId, int>, std::hash<DimId> >'
      required here
    typedef __unordered_map_hasher<key_type, __value_type, hasher>   __hasher;
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cae/main.cpp:18:35: note: in instantiation of template class 'std::unordered_map<DimId, int,
      std::hash<DimId>, std::equal_to<DimId>, std::allocator<std::pair<const DimId, int> > >'
      requested here
   std::unordered_map<DimId, int> mMap;

Regards Johan

**Comment by alexp-sssup** [comment]
std::hash for enum is a C++14 feature, you need to enable it using the ```-std=c++14``` command line option
