### ISSUE TITLE
Docs code samples

### ISSUE THREAD

**Issue by cgoea** [leaningtech/cheerp-meta#84]
The docs [here](https://github.com/leaningtech/cheerp-meta/wiki/JavaScript-interoperability) list the following code example:

```
int stringLength;
client::String* stringFromDom = ...;
__asm__("%1.length" : "=r"(a) : "r"(s));
assert(stringLength == stringFromDom->get_length());
```
Shouldn't the above be

```
int stringLength;
client::String* stringFromDom = ...;
__asm__("%0.length" : "=r"(stringLength) : "r"(stringFromDom));
assert(stringLength == stringFromDom->get_length());
```

namely, `stringLength` instead of `a` & `stringFromDom` instead of `s` and `%0.length` instead of `%1.length` since `"r"(stringFromDom)` is the first input parameter (index 0) while `"=r"(stringLength)` is write only output ?

**Comment by alexp-sssup** [comment]
Thank you for your report. It is now fixed.
