### ISSUE TITLE
Using MakeTypedArray with a std::array as data source creates corrupt data

### ISSUE THREAD

**Issue by johanax** [leaningtech/cheerp-meta#86]
#include <array>
std::array<float, 16> buf = { 0.5, 0.0, 0.0, 0.0,
                               0.0, 0.5, 0.0, 0.0,
                               0.0, 0.0, 0.5, 0.0,
                               0.0, 0.0, 0.0, 1.0};

[[cheerp::genericjs]] void print()
{
  auto ta = cheerp::MakeTypedArray(buf.data(), 16*sizeof(float));
  client::console.log("(*ta)[0]: ", (*ta)[0]);
}

void webMain()
{
  print();
}
output:
(*ta)[0]: 1056964608

**Comment by alexp-sssup** [comment]
Before investigating this we need confirmation that the problem happens using either

1) The official nightly builds on Linux (preferably)
2) The official Cheerp 2.0 RC2 release on other systems

**Comment by alexp-sssup** [comment]
Only happens in wasm mode, we need some time to investigate this

**Comment by alexp-sssup** [comment]
The issue should be fixed in current master
