### ISSUE TITLE
Any "__config" include is not finding features.h header

### ISSUE THREAD

**Issue by aricooperman** [leaningtech/cheerp-meta#88]
I have a C++ file including <string>, using both an Ubuntu 16 and Windows 10 build host, and using both the 2,0 release and building it from source (pulled on 2/22) all fail with same issue:

Windows:
```
C:\cheerp\bin\clang++.exe -target cheerp -cheerp-mode=wasm -cheerp-wasm-loader=test.js -O2 -o xxx_wasm.wasm xxx_wasm.cpp
In file included from xxx_wasm.cpp:5:
In file included from C:\cheerp\bin/../include/c++/v1\string:453:
C:\cheerp\bin/../include/c++/v1\__config:350:10: fatal error: 'features.h' file not found
#include <features.h>
```
Ubuntu:
```
/opt/cheerp/bin/clang++ -target cheerp -cheerp-mode=wasm -cheerp-wasm-loader=test.js -O2 -o xxx_wasm.wasm xxx_wasm.cpp
In file included from xxx_wasm.cpp:5:
In file included from /opt/cheerp/bin/../include/c++/v1/string:453:
/opt/cheerp/bin/../include/c++/v1/__config:350:10: fatal error: 'features.h' file not found
#include <features.h>
```

Error is same for 2.0 release and recent build from source

**Comment by alexp-sssup** [comment]
What headers are being included before ```<string>``` most probably one of them is defined something invalid, most probably the ```__linux__``` macro.

**Comment by alexp-sssup** [comment]
Can you test with a stripped down file like this:

```c++
#include <string>
  
void webMain()
{
}
```

**Comment by aricooperman** [comment]
> What headers are being included before `<string>`? most probably one of them is defined something invalid, most probably the `__linux__` macro.

You are right, we had a __linux__ define before, when I reverse order it includes fine. Thanks!
