### ISSUE TITLE
cheerp bug when compiling c program to js

### ISSUE THREAD

**Issue by SilverNight7350** [leaningtech/cheerp-meta#94]
When compiling a benchmark under SPEC_CPU, when linking the compiled .o program, the following problems occurred. If you can help us solve this problem, we will be very grateful.

> zhouyuchen@ubuntu:~$ cd /home/zhouyuchen/SPEC/benchspec/CPU/505.mcf_r/src/
zhouyuchen@ubuntu:~/SPEC/benchspec/CPU/505.mcf_r/src$ make -f Make.cheerp
clang++ -target cheerp implicit.o mcf.o mcfutil.o output.o pbeampp.o pbla.o pflowup.o psimplex.o pstart.o readmin.o treeup.o -o main.js
Intrinsic name not mangled correctly for type arguments! Should be: llvm.cheerp.cast.user.p0p0struct._Z4node.80.p0p0i8
%struct._Z4node.80** (i8**)* @llvm.cheerp.cast.user.p0p0struct._Z4node.p0p0i8
Intrinsic name not mangled correctly for type arguments! Should be: llvm.cheerp.cast.user.p0p0struct._Z4node.80.p0p0i8
%struct._Z4node.80** (i8**)* @llvm.cheerp.cast.user.p0p0struct._Z4node.p0p0i8
Intrinsic name not mangled correctly for type arguments! Should be: llvm.cheerp.cast.user.p0p0struct._Z4node.80.p0p0i8
%struct._Z4node.80** (i8**)* @llvm.cheerp.cast.user.p0p0struct._Z4node.p0p0i8
Invalid user of intrinsic instruction!
i8* (%struct._Z4node.80*)* bitcast (i8* (%struct._Z4node*)* @llvm.cheerp.cast.user.p0i8.p0struct._Z4node to i8* (%struct._Z4node.80*)*)
Invalid user of intrinsic instruction!
%struct._Z4node.80* (i8*)* bitcast (%struct._Z4node* (i8*)* @llvm.cheerp.cast.user.p0struct._Z4node.p0i8 to %struct._Z4node.80* (i8*)*)
Invalid user of intrinsic instruction!
void (%struct._Z4node.80*)* bitcast (void (%struct._Z4node*)* @llvm.cheerp.deallocate.p0struct._Z4node to void (%struct._Z4node.80*)*)
Invalid user of intrinsic instruction!
%struct._Z4node.80* (i32)* bitcast (%struct._Z4node* (i32)* @llvm.cheerp.allocate.p0struct._Z4node to %struct._Z4node.80* (i32)*)
/opt/cheerp/bin/llvm-link: linked module is broken!
clang-3.7: error: linker command failed with exit code 1 (use -v to see invocation)
Make.cheerp:2: recipe for target 'main' failed
make: *** [main] Error 1

> The compilation environment is:
Ubuntu 18.04.4 LTS
Cheerp 2.0-1 ~ bionic clang version 3.7.0 (based on LLVM 3.7.0svn)
Target: x86_64-pc-linux-gnu
Thread model: posix

Thank you in advance :)

**Comment by alexp-sssup** [comment]
This problem most usually means that the program is declaring the same structure twice, but with different contents. This is ok when dealing with native code but violates the strict type safety requirement of Cheerp. Look up the declaration of the ```node``` structure and make sure no duplicate definition is present.

**Comment by SilverNight7350** [comment]
But why can it be passed when compiling in gcc, and it will prompt duplicate definition errors when using cheerp to convert to JS?

**Comment by alexp-sssup** [comment]
Cheerp's behaviour is consistent with ODR rules in C++. https://en.cppreference.com/w/cpp/language/definition#One_Definition_Rule

When compiling C the rules are more relaxed, and gcc let the code compile. Cheerp needs a stricter level of type safety so it needs to follow C++ rules in this case also when compiling C.

**Comment by SilverNight7350** [comment]
Ok thank you very much for your help
