### ISSUE TITLE
Wasm Tutorial Error on windows

### ISSUE THREAD

**Issue by samcov** [leaningtech/cheerp-meta#99]
When I compile with: clang++ -target cheerp**-wasm** segmented_sieve.cpp -o segmented_sieve.js -O3
I get: **error: unknown target triple 'cheerp**-wasm**', please use -triple or -arch**

Compiling with JS works fine

**Comment by samcov** [comment]
Got it to work by removing the "*"'s

C:\cheerp\bin\clang++ -target **cheerp-wasm** segmented_sieve.cpp -o segmented_sieve.js -O3

**Comment by alexp-sssup** [comment]
Fixed the typo on the tutorial page. Thanks for reporting this.
